import assert from "node:assert/strict";
import { copyFile, readFile, writeFile } from "node:fs/promises";
import { digestFile } from "./package.js";

const directory = "artifacts/release-signed";
const signing = JSON.parse(await readFile(`${directory}/signing.json`, "utf8"));
const verification = JSON.parse(await readFile("artifacts/release-verification.json", "utf8"));
const filename = `stackma-${signing.version}.xpi`;
const actual = await digestFile(`${directory}/${filename}`);
assert.deepEqual(actual, signing.signed);
assert.equal(verification.passed, true);
assert.equal(verification.sha256, actual.sha256);
assert(verification.checks.includes("permanent XPI installation with verified Mozilla signature"));
const sourceName = `stackma-${signing.version}-source.zip`;
await copyFile("artifacts/release-input/source.zip", `${directory}/${sourceName}`);
assert.deepEqual(await digestFile(`${directory}/${sourceName}`), signing.source);
const files = { [filename]: actual, [sourceName]: signing.source };
const record = { ...signing, files, firefox: verification.firefox, firefoxBuildId: verification.buildId };
await writeFile(`${directory}/release.json`, JSON.stringify(record, null, 2) + "\n");
files["release.json"] = await digestFile(`${directory}/release.json`);
await writeFile(`${directory}/SHA256SUMS`, Object.entries(files).map(([name, file]) => `${file.sha256}  ${name}\n`).join(""));
