import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";

const root = new URL("../", import.meta.url);
const source = await readFile(new URL("naming-data/en-v1.json", root), "utf8");
const pack = JSON.parse(source);
assert.equal(pack.schemaVersion, 1);
assert.equal(pack.version, "en-v1");
const adjectives = pack.adjectives;
const nouns = pack.nouns;
const words = [...adjectives, ...nouns];
assert(adjectives.length > 0 && adjectives.length <= 65_536);
assert(nouns.length > 0 && nouns.length <= 65_536);
assert(adjectives.length * nouns.length <= 2 ** 32);
const ids = new Map(words.map((word, index) => [word.id, index]));
assert.equal(ids.size, words.length);
for (const [index, word] of words.entries()) {
  assert.match(word.word, /^[a-z]+$/u);
  assert.equal(word.id, word.word);
  assert.equal(word.role, index < adjectives.length ? "adjective" : "noun");
}

const variants = [];
const allSpellings = new Map(words.map((word, index) => [word.word, index]));
for (const [index, word] of words.entries()) {
  for (const variant of word.spellingVariants) {
    assert.match(variant, /^[a-z]+$/u);
    assert(!allSpellings.has(variant), `Ambiguous spelling variant ${variant}`);
    allSpellings.set(variant, index);
    variants.push([variant, index]);
  }
}

// Rows are indexed by ANY catalog word. Columns are local to the desired role.
// This deliberately preserves cross-role sound/spelling links in manual labels.
const nearAdjectives = [];
const nearNouns = [];
for (const word of words) {
  const neighbors = new Set([word.id, ...word.confusableWith]);
  const adjectiveNeighbors = [];
  const nounNeighbors = [];
  for (const neighbor of neighbors) {
    assert(ids.has(neighbor), `Unknown neighbor ${neighbor}`);
    const index = ids.get(neighbor);
    assert(words[index].id === word.id || words[index].confusableWith.includes(word.id),
      `Asymmetric confusion edge ${word.id}/${neighbor}`);
    if (index < adjectives.length) adjectiveNeighbors.push(index);
    else nounNeighbors.push(index - adjectives.length);
  }
  nearAdjectives.push(adjectiveNeighbors.sort((a, b) => a - b));
  nearNouns.push(nounNeighbors.sort((a, b) => a - b));
}

const pairValues = [];
const pairNames = new Set();
for (const pair of pack.pairs) {
  const adjective = ids.get(pair.adjective);
  const noun = ids.get(pair.noun) - adjectives.length;
  assert(Number.isInteger(adjective) && adjective >= 0 && adjective < adjectives.length);
  assert(Number.isInteger(noun) && noun >= 0 && noun < nouns.length);
  const name = `${words[adjective].word}-${nouns[noun].word}`;
  assert(!pairNames.has(name), `Duplicate edge ${name}`);
  pairNames.add(name);
  pairValues.push(adjective, noun);
}
assert(pairNames.size > 0 && pairNames.size < 2 ** 32);
assert.equal(pairNames.size, pack.statistics.approvedPairs);
const ArrayType = Math.max(adjectives.length, nouns.length) <= 256 ? Uint8Array : Uint16Array;
const packedPairs = new ArrayType(pairValues);
assert.deepEqual([...packedPairs], pairValues, "Pair indices must survive compact integer storage");
assert.deepEqual(
  Array.from({ length: packedPairs.length / 2 }, (_, index) => ({
    adjective: adjectives[packedPairs[index * 2]].id,
    noun: nouns[packedPairs[index * 2 + 1]].id,
  })),
  pack.pairs,
  "Compiled edges must equal the editorial pack, in order",
);

const json = JSON.stringify;
const digest = createHash("sha256").update(source).digest("hex");
const generated = `// Generated by scripts/compile-names.js from naming-data/en-v1.json.
// CMU-derived confusion metadata: redistribution license is CMU-LICENSE.txt.
export const VERSION = ${json(pack.version)};
export const SOURCE_SHA256 = ${json(digest)};
export const ADJECTIVE_COUNT = ${adjectives.length};
export const NOUN_COUNT = ${nouns.length};
export const MAX_WORD_LENGTH = ${Math.max(...allSpellings.keys().map(word => word.length))};
export const WORDS = Object.freeze(${json(words.map(word => word.word))});
/** @type {ReadonlyArray<readonly [string, number]>} */
export const VARIANTS = Object.freeze(${json(variants)});
export const NEAR_ADJECTIVES = Object.freeze(${json(nearAdjectives)}.map(row => Object.freeze(row)));
export const NEAR_NOUNS = Object.freeze(${json(nearNouns)}.map(row => Object.freeze(row)));
export const PAIRS = new ${ArrayType.name}(${json([...packedPairs])});
`;
const catalogPath = new URL("extension/name-catalog.js", root);
const license = await readFile(new URL("naming-data/CMU-LICENSE.txt", root), "utf8");
assert.equal(createHash("sha256").update(license).digest("hex"), pack.provenance.pronunciation.licenseSha256);
const licensePath = new URL("extension/CMU-LICENSE.txt", root);
if (process.argv.includes("--check")) {
  assert.equal(await readFile(catalogPath, "utf8"), generated, "Run node scripts/compile-names.js");
  assert.equal(await readFile(licensePath, "utf8"), license, "Packaged CMU license differs");
} else {
  await writeFile(catalogPath, generated);
  await writeFile(licensePath, license);
}
console.log(`${pack.version}: ${adjectives.length} adjectives, ${nouns.length} nouns, ${pairNames.size} approved edges; ${Buffer.byteLength(generated)} catalog bytes`);
